# Github Dark Colorblind theme for Alacritty

# Default colors
[colors.primary]
background = "#0d1117"
foreground = "#c9d1d9"

# Cursor colors
[colors.cursor]
text = "#0d1117"
cursor = "#c9d1d9"

# Normal colors
[colors.normal]
black = "#484f58"
red = "#ec8e2c"
green = "#58a6ff"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

# Bright colors
[colors.bright]
black = "#6e7681"
red = "#fdac54"
green = "#79c0ff"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

