#!/bin/bash 

export OP_SERVICE_ACCOUNT_TOKEN=op://Restaumatic/sa-token-devcontainer/credential

## ssh revm -tt "docker exec -it devcontainer-dev-1 zsh"
#ssh revm -tt "docker exec -it devcontainer-dev-1 zsh"
et luddite -c "docker exec -it devcontainer-dev-1 zsh "
